### ISSUE TITLE
Configurar Travis

### ISSUE THREAD

**Issue by tomasBustamante** [Axeluck/DragonBallZ#1]
Faltan espacios en el archivo yml entre los guiones y los elementos listados.
```
language: java
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer
```
Acá está la documentación de cómo debe ser el archivo: https://docs.travis-ci.com/user/languages/java/
